version: '3.3'

volumes:
  foodgram_pg_data:
  foodgram_static:
  foodgram_media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - foodgram_static:/app/static_django/
      - foodgram_media:/app/media/
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./local_nginx.conf:/etc/nginx/conf.d/default.conf
      - foodgram_static:/app/static_django/
      - foodgram_media:/app/media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
